---
title: "HW 09: Strings and things"
author: "Jordan Beardslee"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
library(tidyverse)
library(stringr)
library(htmlwidgets)
install.packages("ggthems")
install.packages("RColorBrewer")
install.packages("viridis")
library(ggthemes)
```

#Ch. 14 Section 14.2
```{r}
x <- c("\"", "\\")
x

x <- "\u00b5"
x
```
```{r}
writeLines(x)
```
#14.2.1
```{r}
str_length(c("a", "R for data science", NA))
```
#14.2.2
```{r}
str_c("x", "y")

str_c("x", "y", "z")

str_c("x", "y", sep = ", ")
```
```{r}
x <- c("abc", NA)
str_c("|-", x, "-|")

str_c("|-", str_replace_na(x), "-|")
```
```{r}
str_c("prefix-", c("a", "b", "c"), "-suffix")
```
```{r}
name <- "Hadley"
time_of_day <- "morning"
birthday <- FALSE

str_c(
  "Good ", time_of_day, " ", name,
  if (birthday) " and HAPPY BIRTHDAY",
  "."
)
```
```{r}
str_c(c("x", "y", "z"), collapse = ", ")
```
#14.2.4
```{r}
x <- c("Apple", "Banana", "Pear")
str_sub(x, 1, 3)

str_sub(x, -3, -1)
```
#14.2.4
```{r}
x <- c("apple", "eggplant", "banana")
str_sort(x, locale = "en")

str_sort(x, locale = "haw")
```

#14.3
```{r}
x <- c("apple", "banana", "pear")
str_view(x, "an")

str_view(x, ".a.")
```

```{r}
dot <- "\\."

writeLines(dot)

str_view(c("abc", "a.c", "bef"), "a\\.c")
```

```{r}
x <- "a\\b"
writeLines(x)

str_view(x, "\\\\")
```
#14.3.2
```{r}
x <- c("apple", "banana", "pear")
str_view(x, "^a")

str_view(x, "a$")
```

```{r}
x <- c("apple pie", "apple", "apple cake")
str_view(x, "apple")

str_view(x, "^apples$")
```
#14.3.3
```{r}
str_view(c("abc", "a.c", "a*c", "a c"), "a[.]c")

str_view(c("abc", "a.c", "a*c", "a c"), "a[ ]")
```
#14.3.4
```{r}
x <- "1888 is the longest year in Roman numerals: MDCCCLXXXVIII"
str_view(x, "CC?")

str_view(x, "CC+")

str_view(x, 'C[LX]+')
```

```{r}
str_view(x, "C{2}")

str_view(x, "C{2,}")

str_view(x, "C{2,3}")
```

```{r}
str_view(x, 'C{2,3}?')

str_view(x, 'C[LX]+?')
```
#14.3.5
```{r}
str_view(fruit, "(..)\\1", match = TRUE)
```

```{r}
sum(str_detect(words, "^t"))

mean(str_detect(words, "[aeiou]$"))
```


```{r}
no_vowels_1 <- !str_detect(words, "[aeiou]")

no_vowels_2 <- str_detect(words, "^[^aeiou]+$")
identical(no_vowels_1, no_vowels_2)
```

```{r}
words[str_detect(words, "x$")]

str_subset(words, "x$")
```

```{r}
df <- tibble(
  word = words, 
  i = seq_along(word)
)
df %>% 
  filter(str_detect(word, "x$"))
```

```{r}
x <- c("apple", "banana", "pear")
str_count(x, "a")

mean(str_count(words, "[aeiou]"))
```

```{r}
df %>% 
  mutate(
    vowels = str_count(word, "[aeiou]"),
    consonants = str_count(word, "[^aeiou]")
  )
```

```{r}
str_count("abababa", "aba")

str_view_all("abababa", "aba")
```

```{r}
length(sentences)

head(sentences)
```
```{r}
colours <- c("red", "orange", "yellow", "green", "blue", "purple")
colour_match <- str_c(colours, collapse = "|")
colour_match
```

```{r}
has_colour <- str_subset(sentences, colour_match)
matches <- str_extract(has_colour, colour_match)
head(matches)
```

```{r}
more <- sentences[str_count(sentences, colour_match) > 1]
str_view_all(more, colour_match)
```

```{r}
str_extract(more, colour_match)
```

```{r}
str_extract_all(more, colour_match)
```

```{r}
str_extract_all(more, colour_match, simplify = TRUE)

x <- c("a", "a b", "a b c")
str_extract_all(x, "[a-z]", simplify = TRUE)
```
#14.4.3
```{r}
noun <- "(a|the) ([^ ]+)"

has_noun <- sentences %>%
  str_subset(noun) %>%
  head(10)
has_noun %>% 
  str_extract(noun)
```

```{r}
has_noun %>% 
  str_match(noun)
```

```{r}
tibble(sentence = sentences) %>% 
  tidyr::extract(
    sentence, c("article", "noun"), "(a|the) ([^ ]+)", 
    remove = FALSE
  )
```
#14,4,4
```{r}
x <- c("apple", "pear", "banana")
str_replace(x, "[aeiou]", "-")

str_replace_all(x, "[aeiou]", "-")
```

```{r}
x <- c("1 house", "2 cars", "3 people")
str_replace_all(x, c("1" = "one", "2" = "two", "3" = "three"))
```

```{r}
sentences %>% 
  str_replace("([^ ]+) ([^ ]+) ([^ ]+)", "\\1 \\3 \\2") %>% 
  head(5)
```

```{r}
sentences %>%
  head(5) %>% 
  str_split(" ")
```

```{r}
"a|b|c|d" %>% 
  str_split("\\|") %>% 
  .[[1]]
```

```{r}
sentences %>%
  head(5) %>% 
  str_split(" ", simplify = TRUE)
```

```{r}
fields <- c("Name: Hadley", "Country: NZ", "Age: 35")
fields %>% str_split(": ", n = 2, simplify = TRUE)
```

```{r}
x <- "This is a sentence.  This is another sentence."
str_view_all(x, boundary("word"))
```

```{r}
str_split(x, " ")[[1]]

str_split(x, boundary("word"))[[1]]

```

#14.5
```{r}
str_view(fruit, "nana")

str_view(fruit, regex("nana"))
```

```{r}
bananas <- c("banana", "Banana", "BANANA")
str_view(bananas, "banana")

str_view(bananas, regex("banana", ignore_case = TRUE))
```

```{r}
x <- "Line 1\nLine 2\nLine 3"
str_extract_all(x, "^Line")[[1]]

str_extract_all(x, regex("^Line", multiline = TRUE))[[1]]
```

#Part 1: DNA Strings
```{r}
beta <- read_lines("~/bi485/beardslee_jordan/data/beta_gliadin.txt")
beta
```
#Many strings in one
```{r}
beta_gliadin <- beta %>% 
  str_replace_all("\\s", "\\") %>% 
  str_replace_all("\\d", "\\") %>% 
  str_c(collapse = "") %>% 
  str_to_upper()
beta_gliadin
str_length(beta_gliadin)
```

#Sequence analysis
```{r}
str_count(beta_gliadin, "^ACGT")
str_count(beta_gliadin, "ATG")
str_count(beta_gliadin, "TGA|TAA")
caat_box <- "CCAAT"
tata_box <- "CTATAA"
str_count(beta_gliadin, caat_box)
str_count(beta_gliadin, tata_box)
caat_seq <- "CCAAT.{100,150}ATG"
str_count(beta_gliadin, caat_seq)
tata_seq <- "CTATAA.{50,100}ATG"
str_count(beta_gliadin, tata_seq)
caat_seqs_all <- str_extract_all(beta_gliadin, caat_seq, simplify = TRUE)
caat_seqs_all
str_length(caat_seqs_all)
str_which(caat_seqs_all, tata_box)
promoter <- str_subset(caat_seqs_all, tata_box)
```
```{r}
promoter

str_length(promoter)
```

#Part 2 ants

```{r}
ant <- read.csv("~/bi485/beardslee_jordan/data/ants.csv")
ant
```

#Wrangle the data
```{r}
ant_data <- ant %>%
  select(-c(season, seas.code, trt, plot, sample)) %>%
  gather(key = species, value = abundance, matches("\\w\\.\\w", ignore.case = FALSE))
ant_data
```

```{r}
ants_data <- ant_data %>%
    mutate(
    species = str_replace(
      species,
      pattern = "(^[A-Z]*\\w{3})\\w{3,}\\.(\\w{4})\\w{2,}",
      replacement = "\\1\\2"), year = factor(year, levels = c("2010", "2011"), labels = c("2010", "2011"), ordered = TRUE)) %>% 
  group_by(year, species) %>% 
  summarise(total = sum(abundance, na.rm = TRUE))
ants_data
```

#Plot the data
```{r}
ggplot(data = ants_data, aes(x = reorder(species, total), y = total, group = species)) +
       geom_line(color = "gray") +
         geom_point( aes(shape = year), size = 2) +
         coord_flip() +
         labs(y = "Total Abundance", x = NULL, shape = "Year") +
         theme_minimal()
```

#Part 3
```{r}
flowers <- read.csv("~/bi485/beardslee_jordan/data/flower_size.csv")
flowers
```
```{r}
flower_sizes <- flowers %>%
  filter(!is.na(Flower.number)) %>%
  select(species = Species, cor_length = Corolla.length..cm., throat_width = Corolla.width.throat..cm.) %>%
  separate(species, into = c("genus", "species")) %>%
  group_by(genus, species)
flower_sizes
```
#Import and wrangle
```{r}
pollinators_raw <- read.csv("~/bi485/beardslee_jordan/data/flower_pollinators.csv", na.strings = c("", "NA"))

pollinators_raw

```

```{r}
pollinators <- pollinators_raw %>% 
  select(-c(Color, starts_with("Source"))) %>% 
  filter(!is.na(Pollinator)) %>%
  separate(ï..Species, into = c("genus", "species")) 
pollinators

```

```{r}
pollinators <- pollinators %>% 
    separate(Pollinator, into = "Syndrome", sep = " |, ")
pollinators
```
#Join the datasets
```{r}
phlox <- inner_join(flower_sizes, pollinators, by = c("genus", "species"))
phlox
```
#Plotting
```{r}
ggplot(data = phlox) 
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = Syndrome))
```


