---
title: "HW 10: Maps"
author: "Jordan Beardslee"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(raster)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(maptools)
library(ggmap)
library(marmap)
```
#Part 1
```{r}
usa <- map_data(ma = "state")

us_missouri <- map_data( map = "state",
                         region = "missouri")

us_other <- subset(x = usa, 
                   subset = region %in% c("alabama",
                                          "florida",
                                          "mississippi",
                                          "north carolina"))
```

```{r}
str(usa)
```

```{r}
ggplot() +
  geom_polygon(data = us_other,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = "gray")
```
```{r}
 ggplot() + 
  geom_polygon(data = us_other, 
               aes(x = long, 
                   y = lat, 
                   group = group), 
               fill = "gray") +
  geom_polygon(data = us_missouri, 
               aes(x = long, y = lat, 
                   group = group), 
               fill = "black")
```
```{r}
ggplot() + 
  geom_polygon(data = us_other, 
               aes(x = long, 
                   y = lat, 
                   group = group), 
               fill = "gray") +
  geom_polygon(data = us_missouri, 
               aes(x = long, y = lat, 
                   group = group), 
               fill = "black") +
  geom_polygon(data = usa, 
               aes(x=long, 
                   y = lat, 
                   group = group), 
               fill = NA, 
               color = "black")
```
```{r}
us_map <- ggplot() + 
  geom_polygon(data = us_other, 
               aes(x = long, 
                   y = lat, 
                   group = group), 
               fill = "gray") +
  geom_polygon(data = us_missouri, 
               aes(x = long, y = lat, 
                   group = group), 
               fill = "black") +
  geom_polygon(data = usa, 
               aes(x=long, 
                   y = lat, 
                   group = group), 
               fill = NA, 
               color = "black") + 
  theme_map() +
  coord_fixed(1.3)

us_map
```

```{r}
missouri <- map_data("county", "missouri")
mo_scott <- subset(missouri, subregion %in% c("scott"))

mo_map <- ggplot() + 
  geom_polygon(data = missouri, aes(x=long, y = lat, group = group), fill = NA, color = "black") + 
  geom_polygon(data = mo_scott, aes(x = long, y = lat, group = group), fill = "black") +
  theme_map() +
  coord_fixed(1.3)

mo_map
```
```{r}
us_map + mo_map + plot_layout(ncol = 2, widths = c(1.5,1))
```
#Outline maps: your turn

```{r}
my_us_map <- ggplot() +
  geom_polygon(data = us_missouri,
               aes(x = long, y = lat,
                   group = group),
               fill = "black") +
  geom_polygon(data = usa,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = NA,
               color = "black") +
  theme_map()
coord_fixed(1.3)
my_us_map
```
#County of birth
```{r}
missouri <- map_data("county", "missouri")
mo_jefferson <- subset(missouri, subregion %in% c("jefferson"))

my_mo_map <- ggplot() + 
  geom_polygon(data = missouri, aes(x=long, y = lat, group = group), fill = NA, color = "black") + 
  geom_polygon(data = mo_jefferson, aes(x = long, y = lat, group = group), fill = "black") +
  theme_map() +
  coord_fixed(1.3)

my_mo_map
```
```{r}
missouri <- map_data("county", "missouri")
mo_jefferson <- subset(missouri, subregion %in% c("jefferson"))
mo_lawrence <- subset(missouri, subregion %in% c("lawrence"))
mo_boone <- subset(missouri, subregion %in% c("boone"))

my_mo_map2 <- ggplot() + 
  geom_polygon(data = missouri, aes(x=long, y = lat, group = group), fill = NA, color = "black") + 
  geom_polygon(data = mo_jefferson, aes(x = long, y = lat, group = group), fill = "black") +
  geom_polygon(data = mo_lawrence, aes(x = long, y = lat, group = group), fill = "gray") +
   geom_polygon(data = mo_boone, aes(x = long, y = lat, group = group), fill = "gray") +
  theme_map() +
  coord_fixed(1.3)

my_mo_map2
```

